apiVersion: kp.kpack.io/v1alpha3
kind: DependencyDescriptor
defaultClusterBuilder: base
defaultClusterStack: base
lifecycle:
  image: registry.pivotal.io/tbs-dependencies/lifecycle@sha256:c923a81a1c3908122e29a30bae5886646d6ec26429bad4842c67103636041d93
clusterStores:
- name: default
  sources:
  - image: registry.pivotal.io/tanzu-go-buildpack/go@sha256:53b26a6d91d6f3736a1b54558b649ca09adce44c6f2cab1b31187a5b39f79753
  - image: registry.pivotal.io/tanzu-java-buildpack/java@sha256:7e8e99f27f35944448f8141d07ba158c85b87242d9c9e347f6b108becfbcf552
  - image: registry.pivotal.io/tanzu-nodejs-buildpack/nodejs@sha256:f0d17f5e374c1b14581bc3136d8c6f69d59ef3b35c92d7f247955ace22f932bc
  - image: registry.pivotal.io/tanzu-java-native-image-buildpack/java-native-image@sha256:f634fd5c1bdf873fddc80a243e88b764fbaf7b274334416b638896c6c35f440c
  - image: registry.pivotal.io/tanzu-dotnet-core-buildpack/dotnet-core@sha256:6d57e312e7ac86f78ece4afcc3967e5314fbb71fe592800fd6f0f58bd923945a
  - image: registry.pivotal.io/tanzu-python-buildpack/python@sha256:1222d5f695222597687173b1b8612844f3ccd763eae86e99c3ebacc41390db40
  - image: registry.pivotal.io/tanzu-procfile-buildpack/procfile@sha256:0f34a11769a60568b7f1001f7bb99af6de50177aadd0241c486f59a1e90e0ee9
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_php@sha256:27f003c0ad6d45fd78cd9dbb71ae55b5ba1e599d8facfd98269dd29f42028870
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_nginx@sha256:5798dfecab8a4c67bbc3b956b6bef4474c52197b8949f02b8b866e19bfcde71e
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_httpd@sha256:4e15987d21d3d4f0cbc6be0d3b283db1d3f368eb15d0b1b59d835899c8bf946c
clusterStacks:
- name: tiny
  buildImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/build@sha256:f0d638f9506d3fac6bd98324e982b113fd7866d6ff1186da71f0a95229bfa84f
  runImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/run@sha256:782381e01067bce2169c50d648e69da9dff8c12fe408d4a3f475dac7e985a035
- name: base
  buildImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/build@sha256:49ef507c9db9160a3dea0d07eb0649fe6b6f2a49561729a6e010718d4a978293
  runImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/run@sha256:8ee09c6154a8c9a99f5da07c317102f5c29ad9b1bf2b7742799eb51d9f1a2e56
- name: full
  buildImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/build@sha256:e84fef8869a81171693d2923f2000942ef2cd248d73da8436bb968134bff10fc
  runImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/run@sha256:4ce3f3423e72a638537e25dc25285315ce4bfb7721d2a131ba32ac2b98ba0521
clusterBuilders:
- name: base
  clusterStack: base
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: full
  clusterStack: full
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: tiny
  clusterStack: tiny
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: paketo-buildpacks/procfile
